security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN : ROLE_USER

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
    
        main_login:
            pattern:   ^/(login)?$
            anonymous: true
            
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        main:
            pattern:   ^/
            anonymous: false
            provider:  in_memory
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path:   logout
                target: /
                
                

